server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

logging:
  level:
    com.example.upload: DEBUG
    org.springframework: INFO
#  pattern:
#    console: "%d{yyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

storage:
  path: ${user.dir}/uploads
  chunk-size: 5242880  # 5MB per chunk